# This is a basic workflow to help you get started with Actions

name: Build C Program

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/checkout@v2
      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Compile
        run: |
          gcc -Wall -o Automated_CSV_Data_Analysis main.c \
              CommonDefinitions.c GeneralUtilities.c StringUtilities.c \
              FileUtilities.c DataExtraction.c Integrators.c \
              StatisticalMethods.c DataSetModeling.c DataAnalysis.c \
              DebuggingUtilities.c

    - name: Run tests (if applicable)
        run: ./CSVDataAnalysis

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.






